'use client';

import { useState } from 'react';
import { 
  Copy, 
  Check, 
  Share2, 
  Lightbulb, 
  RotateCcw, 
  Target, 
  Minus, 
  Plus 
} from 'lucide-react';
import { SavedResult } from '@/utils/db';

interface SensitivityDashboardProps {
  result: SavedResult;
}

type TabType = 'camera' | 'ads' | 'gyro' | 'adsGyro';

interface ScopeState {
  no_scope_3rd: number;
  no_scope_1st: number;
  red_dot: number;
  scope_2x: number;
  scope_3x: number;
  scope_4x: number;
  scope_6x: number;
  scope_8x: number;
}

export default function SensitivityDashboard({ result }: SensitivityDashboardProps) {
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedConfig, setCopiedConfig] = useState(false);
  const [activeAnalysisTab, setActiveAnalysisTab] = useState<TabType>('camera');

  // Editable sensitivity values initialized from server calculated settings
  const [sensValues, setSensValues] = useState<{
    camera: ScopeState;
    ads: ScopeState;
    gyro: ScopeState | null;
    adsGyro: ScopeState | null;
  }>(() => {
    const initCategory = (catValues: any) => {
      if (!catValues) return null;
      return {
        no_scope_3rd: catValues.no_scope,
        no_scope_1st: catValues.no_scope, // FPP starts equal to 3rd person
        red_dot: catValues.red_dot,
        scope_2x: catValues.scope_2x,
        scope_3x: catValues.scope_3x,
        scope_4x: catValues.scope_4x,
        scope_6x: catValues.scope_6x,
        scope_8x: catValues.scope_8x,
      };
    };

    return {
      camera: initCategory(result.values.camera)!,
      ads: initCategory(result.values.ads)!,
      gyro: initCategory(result.values.gyro),
      adsGyro: initCategory(result.values.adsGyro),
    };
  });

  const hasGyro = result.inputs.gyroMode !== 'off';

  // Handle slider updates
  const handleSliderChange = (category: TabType, scopeKey: string, val: number) => {
    setSensValues((prev) => {
      const updated = { ...prev };
      if (updated[category]) {
        (updated[category] as any)[scopeKey] = val;
      }
      return updated;
    });
  };

  // Reset slider to server default
  const handleResetSlider = (category: TabType, scopeKey: string) => {
    let defaultVal;
    if (scopeKey === 'no_scope_3rd' || scopeKey === 'no_scope_1st') {
      defaultVal = (result.values as any)[category]?.no_scope;
    } else {
      defaultVal = (result.values as any)[category]?.[scopeKey];
    }
    if (defaultVal !== undefined) {
      handleSliderChange(category, scopeKey, defaultVal);
    }
  };

  // Copy share link
  const copyShareLink = () => {
    const url = window.location.href;
    navigator.clipboard.writeText(url);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  // Copy config settings block
  const copyConfigText = () => {
    let text = `=== AimSync Sensitivity Configuration ===\n`;
    text += `Device: ${result.inputs.deviceTier.toUpperCase()} | FPS: ${result.inputs.fps} | Finger Layout: ${result.inputs.fingerCount} Fingers\n`;
    text += `Combat Playstyle: ${result.inputs.playstyle.toUpperCase()} | Corrective Tuning: ${result.inputs.primaryProblem.toUpperCase()}\n\n`;

    const formatBlock = (title: string, values: ScopeState | null) => {
      if (!values) return '';
      let block = `[${title} Sensitivity]\n`;
      block += `3rd Person No Scope: ${values.no_scope_3rd}%\n`;
      block += `1st Person No Scope: ${values.no_scope_1st}%\n`;
      block += `Red Dot, Holo, Aim Assist: ${values.red_dot}%\n`;
      block += `2x Scope: ${values.scope_2x}%\n`;
      block += `3x Scope: ${values.scope_3x}%\n`;
      block += `4x Scope: ${values.scope_4x}%\n`;
      block += `6x Scope: ${values.scope_6x}%\n`;
      block += `8x Scope: ${values.scope_8x}%\n\n`;
      return block;
    };

    text += formatBlock('Camera', sensValues.camera);
    text += formatBlock('ADS (Firing)', sensValues.ads);
    if (sensValues.gyro) text += formatBlock('Gyroscope', sensValues.gyro);
    if (sensValues.adsGyro) text += formatBlock('ADS Gyroscope', sensValues.adsGyro);

    text += `Generated by AimSync Configurator`;

    navigator.clipboard.writeText(text);
    setCopiedConfig(true);
    setTimeout(() => setCopiedConfig(false), 2000);
  };

  // Get explanation text for active analysis tab
  const getActiveExplanation = () => {
    switch (activeAnalysisTab) {
      case 'camera':
        return result.explanations.camera_explanation;
      case 'ads':
        return result.explanations.ads_explanation;
      case 'gyro':
        return result.explanations.gyro_explanation || 'Gyroscope is disabled.';
      case 'adsGyro':
        return result.explanations.ads_gyro_explanation || 'Gyroscope is disabled.';
      default:
        return '';
    }
  };

  // Render a PUBG-style sensitivity card containing two columns of sliders
  const renderSensCard = (
    category: TabType,
    title: string,
    desc: string,
    maxVal: number
  ) => {
    const values = sensValues[category];
    if (!values) return null;

    const renderSlider = (scopeKey: string, label: string) => {
      const currentVal = (values as any)[scopeKey];
      
      let defaultVal;
      if (scopeKey === 'no_scope_3rd' || scopeKey === 'no_scope_1st') {
        defaultVal = (result.values as any)[category]?.no_scope;
      } else {
        defaultVal = (result.values as any)[category]?.[scopeKey];
      }
      
      const isModified = currentVal !== defaultVal;
      const pct = ((currentVal - 1) / (maxVal - 1)) * 100;

      return (
        <div key={scopeKey} className="space-y-1.5">
          <div className="flex justify-between items-center h-5">
            <span className="text-[11px] font-semibold text-[#8eb0c9] tracking-wide uppercase">
              {label}
            </span>
            <div className="flex items-center gap-2">
              {isModified && (
                <button
                  onClick={() => handleResetSlider(category, scopeKey)}
                  className="text-[9px] font-technical text-primary-yellow hover:underline flex items-center gap-0.5 cursor-pointer"
                  title="Reset to optimal calculated value"
                >
                  <RotateCcw className="w-2.5 h-2.5" />
                  RESET
                </button>
              )}
              <span className="text-[11px] font-bold font-technical text-[#ffd500] border border-[#233f54] bg-[#090f15] px-2 py-0.5 rounded min-w-[44px] text-center select-none">
                {currentVal}%
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* Minus Button */}
            <button
              onClick={() => handleSliderChange(category, scopeKey, Math.max(1, currentVal - 1))}
              className="w-7 h-7 bg-[#101b26] border border-[#223b4f] hover:border-[#00d2ff] hover:text-[#00d2ff] text-[#7ea1bc] flex items-center justify-center font-bold rounded cursor-pointer select-none active:scale-90 transition-all"
            >
              <Minus className="w-3.5 h-3.5" />
            </button>

            {/* Slider track container */}
            <div className="flex-1 px-1 flex items-center relative">
              <input
                type="range"
                min="1"
                max={maxVal}
                value={currentVal}
                onChange={(e) => handleSliderChange(category, scopeKey, Number(e.target.value))}
                className="pubg-slider"
                style={{
                  background: `linear-gradient(to right, #00d2ff 0%, #00d2ff ${pct}%, #0e161f ${pct}%, #0e161f 100%)`
                }}
              />
            </div>

            {/* Plus Button */}
            <button
              onClick={() => handleSliderChange(category, scopeKey, Math.min(maxVal, currentVal + 1))}
              className="w-7 h-7 bg-[#101b26] border border-[#223b4f] hover:border-[#00d2ff] hover:text-[#00d2ff] text-[#7ea1bc] flex items-center justify-center font-bold rounded cursor-pointer select-none active:scale-90 transition-all"
            >
              <Plus className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      );
    };

    return (
      <div className="bg-[#0b1219]/90 border border-[#1b3244] rounded-xl p-5 space-y-4 shadow-xl relative overflow-hidden">
        {/* Subtle grid pattern inside card */}
        <div className="absolute inset-0 opacity-[0.02] pointer-events-none bg-[linear-gradient(to_right,#00d2ff_1px,transparent_1px),linear-gradient(to_bottom,#00d2ff_1px,transparent_1px)] bg-[size:24px_24px]" />
        
        <div className="border-b border-[#1b3244]/60 pb-2 relative z-10">
          <h3 className="font-headline text-base font-extrabold text-[#9cd8ff] tracking-wide uppercase">
            {title}
          </h3>
          <p className="text-[10px] text-[#69859b] mt-0.5">
            {desc}
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-4 relative z-10">
          {/* Left Column */}
          <div className="space-y-4">
            {renderSlider('no_scope_3rd', '3rd Person No Scope')}
            {renderSlider('red_dot', 'Red Dot, Holographic, Aim Assist')}
            {renderSlider('scope_3x', '3x Scope, Win94')}
            {renderSlider('scope_6x', '6x Scope')}
          </div>

          {/* Right Column */}
          <div className="space-y-4">
            {renderSlider('no_scope_1st', '1st Person No Scope')}
            {renderSlider('scope_2x', '2x Scope')}
            {renderSlider('scope_4x', '4x Scope, VSS')}
            {renderSlider('scope_8x', '8x Scope')}
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-6">
      {/* Action Buttons Header */}
      <div className="flex flex-col sm:flex-row gap-3">
        <button
          onClick={copyConfigText}
          className="flex-1 bg-primary-yellow text-background font-headline font-bold py-3.5 px-4 rounded-xl flex items-center justify-center gap-2.5 shadow-[0_4px_16px_rgba(255,215,0,0.25)] hover:bg-white active:scale-95 transition-all text-base border border-primary-yellow/20 cursor-pointer"
        >
          {copiedConfig ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
          {copiedConfig ? 'COPIED CONFIGURATION!' : 'COPY ALL CONFIG'}
        </button>

        <button
          onClick={copyShareLink}
          className="flex-1 bg-surface-card hover:bg-surface-hover text-foreground font-headline font-bold py-3.5 px-4 rounded-xl flex items-center justify-center gap-2.5 border border-border-tactical/40 active:scale-95 transition-all text-base cursor-pointer"
        >
          {copiedLink ? <Check className="w-5 h-5 text-primary-yellow" /> : <Share2 className="w-5 h-5" />}
          {copiedLink ? 'LINK COPIED!' : 'COPY SHARE LINK'}
        </button>
      </div>

      {/* Dynamic Tactical Analysis Panel with Sub-Tabs */}
      <div className="bg-[#0b1219]/90 border border-[#1b3244] rounded-xl p-5 space-y-4 shadow-xl relative overflow-hidden animate-scan">
        <div className="flex border-b border-[#1b3244]/40 pb-2 overflow-x-auto no-scrollbar gap-2">
          <div className="bg-primary-yellow/15 p-1 rounded-lg h-fit text-primary-yellow flex-shrink-0 mr-1 animate-pulse">
            <Lightbulb className="w-4 h-4" />
          </div>
          {[
            { id: 'camera', label: 'LOOK ANALYSIS' },
            { id: 'ads', label: 'ADS RECOIL ANALYSIS' },
            { id: 'gyro', label: 'GYRO ANALYSIS', show: hasGyro },
          ].map(
            (tab) =>
              (tab.show !== false) && (
                <button
                  key={tab.id}
                  onClick={() => setActiveAnalysisTab(tab.id as TabType)}
                  className={`text-[10px] font-headline font-bold tracking-widest px-2.5 py-1 transition-all rounded cursor-pointer ${
                    activeAnalysisTab === tab.id
                      ? 'bg-primary-yellow/20 text-primary-yellow border border-primary-yellow/30'
                      : 'text-text-muted hover:text-foreground border border-transparent'
                  }`}
                >
                  {tab.label}
                </button>
              )
          )}
        </div>
        <div className="space-y-1">
          <p className="text-xs text-text-muted leading-relaxed select-none">
            {getActiveExplanation()}
          </p>
        </div>
      </div>

      {/* PUBG Mobile Themed Sensitivity Cards Stack */}
      <div className="space-y-5">
        {renderSensCard(
          'camera', 
          'Camera', 
          'Affects the sensitivity of the camera when the screen is swiped without firing.', 
          200
        )}
        
        {renderSensCard(
          'ads', 
          'ADS Sensitivity', 
          'Affects the sensitivity of the camera when the screen is swiped while firing. Can be used to keep the barrel down.', 
          200
        )}

        {hasGyro && renderSensCard(
          'gyro', 
          'Gyroscope', 
          'When the Gyroscope is activated, the sensitivity of the tilt camera controls can be adjusted.', 
          400
        )}

        {hasGyro && renderSensCard(
          'adsGyro', 
          'ADS Gyroscope', 
          'When the Gyroscope is activated, the sensitivity of the tilt camera controls during shooting can be adjusted.', 
          400
        )}
      </div>

      {/* Shooting Range Simulator (Coming Soon Placeholder) */}
      <div className="bg-[#0b1219]/90 border border-[#1b3244] rounded-xl p-5 space-y-4 relative overflow-hidden">
        <div className="flex justify-between items-center border-b border-[#1b3244]/60 pb-2">
          <h3 className="font-headline text-base font-extrabold text-[#9cd8ff] tracking-wide uppercase flex items-center gap-2">
            <Target className="w-5 h-5 text-primary-yellow animate-pulse" />
            SHOOTING RANGE SIMULATOR
          </h3>
          <span className="font-technical text-[9px] bg-primary-yellow/15 text-primary-yellow border border-primary-yellow/30 px-2.5 py-0.5 rounded tracking-widest font-black">
            COMING SOON
          </span>
        </div>

        <div className="relative border border-[#1b3244]/30 rounded-xl bg-background/20 p-8 text-center flex flex-col items-center justify-center min-h-[200px] overflow-hidden">
          <div className="absolute inset-0 opacity-[0.03] pointer-events-none bg-[linear-gradient(to_right,#ffd700_1px,transparent_1px),linear-gradient(to_bottom,#ffd700_1px,transparent_1px)] bg-[size:15px_15px]" />
          
          <div className="relative z-10 space-y-3 max-w-sm">
            <div className="mx-auto w-12 h-12 rounded-full border border-primary-yellow/20 bg-primary-yellow/5 flex items-center justify-center text-primary-yellow mb-2 animate-pulse">
              <Target className="w-6 h-6" />
            </div>
            <h4 className="font-headline text-sm font-extrabold text-foreground tracking-wider uppercase">PHYSICS ENGINE CALIBRATION</h4>
            <p className="text-xs text-[#69859b] leading-relaxed">
              Our interactive 3D weapon recoil simulator is currently undergoing server-side physics engine calibration. Check back soon to test your sensitivity configurations.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
